ci.yml file changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,14 +17,14 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Run PHP syntax check
-              run: |
-                  set -e
-                  exit_code=0
-                  find . -path ./vendor -prune -o -type f -name "*.php" -exec php -l {} \; || exit_code=$?
-                  if [ $exit_code -ne 0 ]; then
-                    echo "Syntax errors detected"
-                    exit 1
-                  fi
+        run: |
+            set -e
+            exit_code=0
+            find . -path ./vendor -prune -o -type f -name "*.php" -exec php -l {} \; || exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              echo "Syntax errors detected"
+              exit 1
+            fi
                  
       - name: Set up PHP
         uses: shivammathur/setup-php@v2
